Public Class ClassHolerite_completoAcao
    Dim posicaoCorpo As Integer = 0
    Public Shared Function GetHoleriteCompleto(strReferencia) As List(Of ClassHolerite_completo)


        Dim strRef As String = strReferencia
        Dim lista As New List(Of ClassHolerite_completo)

        Dim hol_cab As List(Of ClassFolha_holerite_close_cab) = ClassFolha_holerite_close_cabAcao.GetHoleriteCabDB(strRef)
        Dim hol_corp As List(Of ClassFolha_holerite_close_corp) = ClassFolha_holerite_close_corpAcao.GetHoleriteCorpDB(strRef)


        Try

            Dim intPosicaoInicioCorpo As Integer = 0
            Dim intPosicaoFimCorpo As Integer = -1
            Dim intIndiceMaximo As Integer = hol_corp.Count - 1
            For i = 0 To hol_cab.Count - 1
                For j = intPosicaoInicioCorpo To hol_corp.Count - 1
                    If hol_cab(i).Class_id_fcab = hol_corp(j).Class_ID_folha_close_cab Then
                        intPosicaoFimCorpo += 1
                    Else
                        Exit For
                    End If
                Next

                lista.Add(New ClassHolerite_completo() With
                        {
                        .Class_id_fcab = hol_cab(i).Class_id_fcab,
                        .Class_keyCol = hol_cab(i).Class_keyCol,
                        .Class_nome = hol_cab(i).Class_nome,
                        .Class_cbo = hol_cab(i).Class_cbo,
                        .Class_Cargo = hol_cab(i).Class_Cargo,
                        .Class_ref = hol_cab(i).Class_ref,
                        .Class_ref_Mes_Ano = hol_cab(i).Class_ref_Mes_Ano,
                        .Class_local = hol_cab(i).Class_local,
                        .Class_setor = hol_cab(i).Class_setor,
                        .Class_processo_origem = "Folha de Pagamento",
                        .Class_SB = hol_cab(i).Class_SB,
                        .Class_sbINSS = hol_cab(i).Class_sbINSS,
                        .Class_sbFGTS = hol_cab(i).Class_sbFGTS,
                        .Class_sbIRRF = hol_cab(i).Class_sbIRRF,
                        .class_DSRvariavel_base = hol_cab(i).Class_sbDRSvariavel,
                        .class_DsrVariavel_valor = hol_cab(i).Class_DSRvariavel,
                .Class_IRRFfaixa = hol_cab(i).Class_IRRFfaixa,
                        .Class_INSScol = hol_cab(i).Class_INSScol,
                        .Class_FGTScol = hol_cab(i).Class_FGTScol,
                        .Class_dias_trabalhadosNaReferencia = hol_cab(i).Class_dias_trabalhadosNaReferencia,
                        .Class_IRcol = hol_cab(i).Class_IRcol,
                        .Class_IRRFdesconto = hol_cab(i).Class_IRRFdesconto,
                        .Class_IRRFdep = hol_cab(i).Class_IRRFdep,
                        .Class_sfDep = hol_cab(i).Class_sfDep,
                        .Class_Tdebitos = hol_cab(i).Class_Tdebitos,
                        .Class_Tcreditos = hol_cab(i).Class_Tcreditos,
                        .Class_Tliquido = hol_cab(i).Class_Tliquido,
                        .Class_hora_trabalhada = hol_cab(i).Class_hora_trabalhada,
                        .Class_valor_hora_trabalhada = hol_cab(i).Class_valor_hora_trabalhada,
                        .Class_valor_dia_trabalhado = hol_cab(i).Class_valor_dia_trabalhado,
                        .Class_dias_uteis = hol_cab(i).Class_dias_uteis,
                        .Class_descansos_ref = hol_cab(i).Class_descansos_ref,
                        .Class_Ferias_proporcional = hol_cab(i).Class_Ferias_proporcional,
                        .Class_ferias_terco = hol_cab(i).Class_ferias_terco,
                        .Class_decimo_terceiro = hol_cab(i).Class_decimo_terceiro,
                        .Class_descanso_semanal = hol_cab(i).Class_descanso_semanal,
                        .Class_INSSpercentualTotal = hol_cab(i).Class_INSSpercentualTotal,
                        .Class_INSSpatronalValor = hol_cab(i).Class_INSSpatronalValor,
                        .Class_INSSvalorTotal = hol_cab(i).Class_INSSvalorTotal,
                        .Class_total_INSSpatronal_FGTSreferencia = hol_cab(i).Class_total_INSSpatronal_FGTSreferencia,
                        .Class_referencia_total = hol_cab(i).Class_referencia_total,
                        .Class_colaborador_custo_total_referencia = hol_cab(i).Class_colaborador_custo_total_referencia,
                        .Class_admissao_data = hol_cab(i).Class_admissao_data,
                        .Class_admissao_referencia = hol_cab(i).Class_admissao_referencia,
                        .Class_referencia_provisionado = hol_cab(i).Class_referencia_provisionado,
                        .Class_diasTrabalhadosNaReferencia = hol_cab(i).Class_diasTrabalhadosNaReferencia,
                        .Class_emp_RazaoSocial = hol_cab(i).Class_emp_RazaoSocial,
                        .Class_emp_Endereco = hol_cab(i).Class_emp_Endereco,
                        .Class_emp_CNPJ = hol_cab(i).Class_emp_CNPJ,
                        .Class_emp_Local = hol_cab(i).Class_emp_Local,
                        .Class_rubrica_0 = IIf(intPosicaoInicioCorpo <= intPosicaoFimCorpo, hol_corp(intPosicaoInicioCorpo).Class_rubrica, ""),
                        .Class_descricao_0 = IIf(intPosicaoInicioCorpo <= intPosicaoFimCorpo, hol_corp(intPosicaoInicioCorpo).Class_descricao, ""),
                        .Class_QTO_0 = IIf(intPosicaoInicioCorpo <= intPosicaoFimCorpo, hol_corp(intPosicaoInicioCorpo).Class_QTO, 0),
                        .Class_UN_0 = IIf(intPosicaoInicioCorpo <= intPosicaoFimCorpo, hol_corp(intPosicaoInicioCorpo).Class_UN, ""),
                        .Class_base_INSS_0 = IIf(intPosicaoInicioCorpo <= intPosicaoFimCorpo, hol_corp(intPosicaoInicioCorpo).Class_base_INSS, ""),
                        .Class_base_FGTS_0 = IIf(intPosicaoInicioCorpo <= intPosicaoFimCorpo, hol_corp(intPosicaoInicioCorpo).Class_base_FGTS, ""),
                        .Class_base_IR_0 = IIf(intPosicaoInicioCorpo <= intPosicaoFimCorpo, hol_corp(intPosicaoInicioCorpo).Class_base_IR, ""),
                        .Class_tipo_financeiro_0 = IIf(intPosicaoInicioCorpo <= intPosicaoFimCorpo, hol_corp(intPosicaoInicioCorpo).Class_tipo_financeiro, ""),
                        .Class_valor_0 = IIf(intPosicaoInicioCorpo <= intPosicaoFimCorpo, hol_corp(intPosicaoInicioCorpo).Class_valor, 0),
                        .Class_valor_base_0 = IIf(intPosicaoInicioCorpo <= intPosicaoFimCorpo, hol_corp(intPosicaoInicioCorpo).Class_valor_base, 0),
                        .Class_debito_holerite_0 = IIf(intPosicaoInicioCorpo <= intPosicaoFimCorpo, hol_corp(intPosicaoInicioCorpo).Class_debito_holerite, 0),
                        .Class_credito_holerite_0 = IIf(intPosicaoInicioCorpo <= intPosicaoFimCorpo, hol_corp(intPosicaoInicioCorpo).Class_credito_holerite, 0),
                        .Class_rubrica_1 = IIf(intPosicaoInicioCorpo + 1 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 1 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 1)).Class_rubrica, ""),
                        .Class_descricao_1 = IIf(intPosicaoInicioCorpo + 1 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 1 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 1)).Class_descricao, ""),
                        .Class_QTO_1 = IIf(intPosicaoInicioCorpo + 1 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 1 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 1)).Class_QTO, 0),
                        .Class_UN_1 = IIf(intPosicaoInicioCorpo + 1 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 1 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 1)).Class_UN, ""),
                        .Class_base_INSS_1 = IIf(intPosicaoInicioCorpo + 1 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 1 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 1)).Class_base_INSS, ""),
                        .Class_base_FGTS_1 = IIf(intPosicaoInicioCorpo + 1 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 1 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 1)).Class_base_FGTS, ""),
                        .Class_base_IR_1 = IIf(intPosicaoInicioCorpo + 1 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 1 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 1)).Class_base_IR, ""),
                        .Class_tipo_financeiro_1 = IIf(intPosicaoInicioCorpo + 1 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 1 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 1)).Class_tipo_financeiro, ""),
                        .Class_valor_1 = IIf(intPosicaoInicioCorpo + 1 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 1 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 1)).Class_valor, 0),
                        .Class_valor_base_1 = IIf(intPosicaoInicioCorpo + 1 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 1 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 1)).Class_valor_base, 0),
                        .Class_debito_holerite_1 = IIf(intPosicaoInicioCorpo + 1 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 1 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 1)).Class_debito_holerite, 0),
                        .Class_credito_holerite_1 = IIf(intPosicaoInicioCorpo + 1 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 1 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 1)).Class_credito_holerite, 0),
                        .Class_rubrica_2 = IIf(intPosicaoInicioCorpo + 2 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 2 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 2)).Class_rubrica, ""),
                        .Class_descricao_2 = IIf(intPosicaoInicioCorpo + 2 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 2 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 2)).Class_descricao, ""),
                        .Class_QTO_2 = IIf(intPosicaoInicioCorpo + 2 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 2 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 2)).Class_QTO, 0),
                        .Class_UN_2 = IIf(intPosicaoInicioCorpo + 2 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 2 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 2)).Class_UN, ""),
                        .Class_base_INSS_2 = IIf(intPosicaoInicioCorpo + 2 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 2 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 2)).Class_base_INSS, ""),
                        .Class_base_FGTS_2 = IIf(intPosicaoInicioCorpo + 2 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 2 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 2)).Class_base_FGTS, ""),
                        .Class_base_IR_2 = IIf(intPosicaoInicioCorpo + 2 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 2 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 2)).Class_base_IR, ""),
                        .Class_tipo_financeiro_2 = IIf(intPosicaoInicioCorpo + 2 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 2 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 2)).Class_tipo_financeiro, ""),
                        .Class_valor_2 = IIf(intPosicaoInicioCorpo + 2 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 2 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 2)).Class_valor, 0),
                        .Class_valor_base_2 = IIf(intPosicaoInicioCorpo + 2 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 2 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 2)).Class_valor_base, 0),
                        .Class_debito_holerite_2 = IIf(intPosicaoInicioCorpo + 2 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 2 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 2)).Class_debito_holerite, 0),
                        .Class_credito_holerite_2 = IIf(intPosicaoInicioCorpo + 2 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 2 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 2)).Class_credito_holerite, 0),
                        .Class_rubrica_3 = IIf(intPosicaoInicioCorpo + 3 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 3 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 3)).Class_rubrica, ""),
                        .Class_descricao_3 = IIf(intPosicaoInicioCorpo + 3 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 3 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 3)).Class_descricao, ""),
                        .Class_QTO_3 = IIf(intPosicaoInicioCorpo + 3 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 3 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 3)).Class_QTO, 0),
                        .Class_UN_3 = IIf(intPosicaoInicioCorpo + 3 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 3 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 3)).Class_UN, ""),
                        .Class_base_INSS_3 = IIf(intPosicaoInicioCorpo + 3 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 3 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 3)).Class_base_INSS, ""),
                        .Class_base_FGTS_3 = IIf(intPosicaoInicioCorpo + 3 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 3 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 3)).Class_base_FGTS, ""),
                        .Class_base_IR_3 = IIf(intPosicaoInicioCorpo + 3 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 3 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 3)).Class_base_IR, ""),
                        .Class_tipo_financeiro_3 = IIf(intPosicaoInicioCorpo + 3 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 3 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 3)).Class_tipo_financeiro, ""),
                        .Class_valor_3 = IIf(intPosicaoInicioCorpo + 3 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 3 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 3)).Class_valor, 0),
                        .Class_valor_base_3 = IIf(intPosicaoInicioCorpo + 3 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 3 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 3)).Class_valor_base, 0),
                        .Class_debito_holerite_3 = IIf(intPosicaoInicioCorpo + 3 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 3 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 3)).Class_debito_holerite, 0),
                        .Class_credito_holerite_3 = IIf(intPosicaoInicioCorpo + 3 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 3 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 3)).Class_credito_holerite, 0),
                        .Class_rubrica_4 = IIf(intPosicaoInicioCorpo + 4 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 4 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 4)).Class_rubrica, ""),
                        .Class_descricao_4 = IIf(intPosicaoInicioCorpo + 4 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 4 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 4)).Class_descricao, ""),
                        .Class_QTO_4 = IIf(intPosicaoInicioCorpo + 4 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 4 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 4)).Class_QTO, 0),
                        .Class_UN_4 = IIf(intPosicaoInicioCorpo + 4 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 4 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 4)).Class_UN, ""),
                        .Class_base_INSS_4 = IIf(intPosicaoInicioCorpo + 4 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 4 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 4)).Class_base_INSS, ""),
                        .Class_base_FGTS_4 = IIf(intPosicaoInicioCorpo + 4 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 4 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 4)).Class_base_FGTS, ""),
                        .Class_base_IR_4 = IIf(intPosicaoInicioCorpo + 4 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 4 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 4)).Class_base_IR, ""),
                        .Class_tipo_financeiro_4 = IIf(intPosicaoInicioCorpo + 4 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 4 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 4)).Class_tipo_financeiro, ""),
                        .Class_valor_4 = IIf(intPosicaoInicioCorpo + 4 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 4 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 4)).Class_valor, 0),
                        .Class_valor_base_4 = IIf(intPosicaoInicioCorpo + 4 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 4 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 4)).Class_valor_base, 0),
                        .Class_debito_holerite_4 = IIf(intPosicaoInicioCorpo + 4 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 4 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 4)).Class_debito_holerite, 0),
                        .Class_credito_holerite_4 = IIf(intPosicaoInicioCorpo + 4 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 4 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 4)).Class_credito_holerite, 0),
                        .Class_rubrica_5 = IIf(intPosicaoInicioCorpo + 5 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 5 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 5)).Class_rubrica, ""),
                        .Class_descricao_5 = IIf(intPosicaoInicioCorpo + 5 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 5 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 5)).Class_descricao, ""),
                        .Class_QTO_5 = IIf(intPosicaoInicioCorpo + 5 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 5 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 5)).Class_QTO, 0),
                        .Class_UN_5 = IIf(intPosicaoInicioCorpo + 5 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 5 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 5)).Class_UN, ""),
                        .Class_base_INSS_5 = IIf(intPosicaoInicioCorpo + 5 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 5 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 5)).Class_base_INSS, ""),
                        .Class_base_FGTS_5 = IIf(intPosicaoInicioCorpo + 5 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 5 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 5)).Class_base_FGTS, ""),
                        .Class_base_IR_5 = IIf(intPosicaoInicioCorpo + 5 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 5 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 5)).Class_base_IR, ""),
                        .Class_tipo_financeiro_5 = IIf(intPosicaoInicioCorpo + 5 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 5 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 5)).Class_tipo_financeiro, ""),
                        .Class_valor_5 = IIf(intPosicaoInicioCorpo + 5 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 5 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 5)).Class_valor, 0),
                        .Class_valor_base_5 = IIf(intPosicaoInicioCorpo + 5 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 5 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 5)).Class_valor_base, 0),
                        .Class_debito_holerite_5 = IIf(intPosicaoInicioCorpo + 5 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 5 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 5)).Class_debito_holerite, 0),
                        .Class_credito_holerite_5 = IIf(intPosicaoInicioCorpo + 5 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 5 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 5)).Class_credito_holerite, 0),
                        .Class_rubrica_6 = IIf(intPosicaoInicioCorpo + 6 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 6 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 6)).Class_rubrica, ""),
                        .Class_descricao_6 = IIf(intPosicaoInicioCorpo + 6 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 6 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 6)).Class_descricao, ""),
                        .Class_QTO_6 = IIf(intPosicaoInicioCorpo + 6 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 6 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 6)).Class_QTO, 0),
                        .Class_UN_6 = IIf(intPosicaoInicioCorpo + 6 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 6 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 6)).Class_UN, ""),
                        .Class_base_INSS_6 = IIf(intPosicaoInicioCorpo + 6 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 6 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 6)).Class_base_INSS, ""),
                        .Class_base_FGTS_6 = IIf(intPosicaoInicioCorpo + 6 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 6 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 6)).Class_base_FGTS, ""),
                        .Class_base_IR_6 = IIf(intPosicaoInicioCorpo + 6 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 6 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 6)).Class_base_IR, ""),
                        .Class_tipo_financeiro_6 = IIf(intPosicaoInicioCorpo + 6 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 6 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 6)).Class_tipo_financeiro, ""),
                        .Class_valor_6 = IIf(intPosicaoInicioCorpo + 6 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 6 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 6)).Class_valor, 0),
                        .Class_valor_base_6 = IIf(intPosicaoInicioCorpo + 6 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 6 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 6)).Class_valor_base, 0),
                        .Class_debito_holerite_6 = IIf(intPosicaoInicioCorpo + 6 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 6 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 6)).Class_debito_holerite, 0),
                        .Class_credito_holerite_6 = IIf(intPosicaoInicioCorpo + 6 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 6 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 6)).Class_credito_holerite, 0),
                        .Class_rubrica_7 = IIf(intPosicaoInicioCorpo + 7 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 7 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 7)).Class_rubrica, ""),
                        .Class_descricao_7 = IIf(intPosicaoInicioCorpo + 7 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 7 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 7)).Class_descricao, ""),
                        .Class_QTO_7 = IIf(intPosicaoInicioCorpo + 7 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 7 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 7)).Class_QTO, 0),
                        .Class_UN_7 = IIf(intPosicaoInicioCorpo + 7 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 7 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 7)).Class_UN, ""),
                        .Class_base_INSS_7 = IIf(intPosicaoInicioCorpo + 7 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 7 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 7)).Class_base_INSS, ""),
                        .Class_base_FGTS_7 = IIf(intPosicaoInicioCorpo + 7 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 7 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 7)).Class_base_FGTS, ""),
                        .Class_base_IR_7 = IIf(intPosicaoInicioCorpo + 7 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 7 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 7)).Class_base_IR, ""),
                        .Class_tipo_financeiro_7 = IIf(intPosicaoInicioCorpo + 7 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 7 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 7)).Class_tipo_financeiro, ""),
                        .Class_valor_7 = IIf(intPosicaoInicioCorpo + 7 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 7 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 7)).Class_valor, 0),
                        .Class_valor_base_7 = IIf(intPosicaoInicioCorpo + 7 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 7 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 7)).Class_valor_base, 0),
                        .Class_debito_holerite_7 = IIf(intPosicaoInicioCorpo + 7 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 7 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 7)).Class_debito_holerite, 0),
                        .Class_credito_holerite_7 = IIf(intPosicaoInicioCorpo + 7 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 7 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 7)).Class_credito_holerite, 0),
                        .Class_rubrica_8 = IIf(intPosicaoInicioCorpo + 8 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 8 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 8)).Class_rubrica, ""),
                        .Class_descricao_8 = IIf(intPosicaoInicioCorpo + 8 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 8 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 8)).Class_descricao, ""),
                        .Class_QTO_8 = IIf(intPosicaoInicioCorpo + 8 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 8 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 8)).Class_QTO, 0),
                        .Class_UN_8 = IIf(intPosicaoInicioCorpo + 8 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 8 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 8)).Class_UN, ""),
                        .Class_base_INSS_8 = IIf(intPosicaoInicioCorpo + 8 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 8 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 8)).Class_base_INSS, ""),
                        .Class_base_FGTS_8 = IIf(intPosicaoInicioCorpo + 8 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 8 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 8)).Class_base_FGTS, ""),
                        .Class_base_IR_8 = IIf(intPosicaoInicioCorpo + 8 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 8 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 8)).Class_base_IR, ""),
                        .Class_tipo_financeiro_8 = IIf(intPosicaoInicioCorpo + 8 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 8 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 8)).Class_tipo_financeiro, ""),
                        .Class_valor_8 = IIf(intPosicaoInicioCorpo + 8 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 8 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 8)).Class_valor, 0),
                        .Class_valor_base_8 = IIf(intPosicaoInicioCorpo + 8 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 8 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 8)).Class_valor_base, 0),
                        .Class_debito_holerite_8 = IIf(intPosicaoInicioCorpo + 8 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 8 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 8)).Class_debito_holerite, 0),
                        .Class_credito_holerite_8 = IIf(intPosicaoInicioCorpo + 8 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 8 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 8)).Class_credito_holerite, 0),
                        .Class_rubrica_9 = IIf(intPosicaoInicioCorpo + 9 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 9 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 9)).Class_rubrica, ""),
                        .Class_descricao_9 = IIf(intPosicaoInicioCorpo + 9 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 9 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 9)).Class_descricao, ""),
                        .Class_QTO_9 = IIf(intPosicaoInicioCorpo + 9 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 9 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 9)).Class_QTO, 0),
                        .Class_UN_9 = IIf(intPosicaoInicioCorpo + 9 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 9 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 9)).Class_UN, ""),
                        .Class_base_INSS_9 = IIf(intPosicaoInicioCorpo + 9 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 9 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 9)).Class_base_INSS, ""),
                        .Class_base_FGTS_9 = IIf(intPosicaoInicioCorpo + 9 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 9 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 9)).Class_base_FGTS, ""),
                        .Class_base_IR_9 = IIf(intPosicaoInicioCorpo + 9 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 9 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 9)).Class_base_IR, ""),
                        .Class_tipo_financeiro_9 = IIf(intPosicaoInicioCorpo + 9 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 9 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 9)).Class_tipo_financeiro, ""),
                        .Class_valor_9 = IIf(intPosicaoInicioCorpo + 9 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 9 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 9)).Class_valor, 0),
                        .Class_valor_base_9 = IIf(intPosicaoInicioCorpo + 9 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 9 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 9)).Class_valor_base, 0),
                        .Class_debito_holerite_9 = IIf(intPosicaoInicioCorpo + 9 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 9 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 9)).Class_debito_holerite, 0),
                        .Class_credito_holerite_9 = IIf(intPosicaoInicioCorpo + 9 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 9 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 9)).Class_credito_holerite, 0),
                        .Class_rubrica_10 = IIf(intPosicaoInicioCorpo + 10 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 10 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 10)).Class_rubrica, ""),
                        .Class_descricao_10 = IIf(intPosicaoInicioCorpo + 10 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 10 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 10)).Class_descricao, ""),
                        .Class_QTO_10 = IIf(intPosicaoInicioCorpo + 10 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 10 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 10)).Class_QTO, 0),
                        .Class_UN_10 = IIf(intPosicaoInicioCorpo + 10 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 10 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 10)).Class_UN, ""),
                        .Class_base_INSS_10 = IIf(intPosicaoInicioCorpo + 10 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 10 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 10)).Class_base_INSS, ""),
                        .Class_base_FGTS_10 = IIf(intPosicaoInicioCorpo + 10 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 10 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 10)).Class_base_FGTS, ""),
                        .Class_base_IR_10 = IIf(intPosicaoInicioCorpo + 10 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 10 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 10)).Class_base_IR, ""),
                        .Class_tipo_financeiro_10 = IIf(intPosicaoInicioCorpo + 10 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 10 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 10)).Class_tipo_financeiro, ""),
                        .Class_valor_10 = IIf(intPosicaoInicioCorpo + 10 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 10 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 10)).Class_valor, 0),
                        .Class_valor_base_10 = IIf(intPosicaoInicioCorpo + 10 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 10 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 10)).Class_valor_base, 0),
                        .Class_debito_holerite_10 = IIf(intPosicaoInicioCorpo + 10 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 10 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 10)).Class_debito_holerite, 0),
                        .Class_credito_holerite_10 = IIf(intPosicaoInicioCorpo + 10 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 10 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 10)).Class_credito_holerite, 0),
                        .Class_rubrica_11 = IIf(intPosicaoInicioCorpo + 11 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 11 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 11)).Class_rubrica, ""),
                        .Class_descricao_11 = IIf(intPosicaoInicioCorpo + 11 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 11 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 11)).Class_descricao, ""),
                        .Class_QTO_11 = IIf(intPosicaoInicioCorpo + 11 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 11 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 11)).Class_QTO, 0),
                        .Class_UN_11 = IIf(intPosicaoInicioCorpo + 11 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 11 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 11)).Class_UN, ""),
                        .Class_base_INSS_11 = IIf(intPosicaoInicioCorpo + 11 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 11 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 11)).Class_base_INSS, ""),
                        .Class_base_FGTS_11 = IIf(intPosicaoInicioCorpo + 11 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 11 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 11)).Class_base_FGTS, ""),
                        .Class_base_IR_11 = IIf(intPosicaoInicioCorpo + 11 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 11 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 11)).Class_base_IR, ""),
                        .Class_tipo_financeiro_11 = IIf(intPosicaoInicioCorpo + 11 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 11 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 11)).Class_tipo_financeiro, ""),
                        .Class_valor_11 = IIf(intPosicaoInicioCorpo + 11 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 11 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 11)).Class_valor, 0),
                        .Class_valor_base_11 = IIf(intPosicaoInicioCorpo + 11 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 11 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 11)).Class_valor_base, 0),
                        .Class_debito_holerite_11 = IIf(intPosicaoInicioCorpo + 11 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 11 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 11)).Class_debito_holerite, 0),
                        .Class_credito_holerite_11 = IIf(intPosicaoInicioCorpo + 11 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 11 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 11)).Class_credito_holerite, 0),
                        .Class_rubrica_12 = IIf(intPosicaoInicioCorpo + 12 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 12 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 12)).Class_rubrica, ""),
                        .Class_descricao_12 = IIf(intPosicaoInicioCorpo + 12 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 12 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 12)).Class_descricao, ""),
                        .Class_QTO_12 = IIf(intPosicaoInicioCorpo + 12 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 12 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 12)).Class_QTO, 0),
                        .Class_UN_12 = IIf(intPosicaoInicioCorpo + 12 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 12 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 12)).Class_UN, ""),
                        .Class_base_INSS_12 = IIf(intPosicaoInicioCorpo + 12 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 12 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 12)).Class_base_INSS, ""),
                        .Class_base_FGTS_12 = IIf(intPosicaoInicioCorpo + 12 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 12 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 12)).Class_base_FGTS, ""),
                        .Class_base_IR_12 = IIf(intPosicaoInicioCorpo + 12 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 12 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 12)).Class_base_IR, ""),
                        .Class_tipo_financeiro_12 = IIf(intPosicaoInicioCorpo + 12 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 12 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 12)).Class_tipo_financeiro, ""),
                        .Class_valor_12 = IIf(intPosicaoInicioCorpo + 12 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 12 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 12)).Class_valor, 0),
                        .Class_valor_base_12 = IIf(intPosicaoInicioCorpo + 12 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 12 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 12)).Class_valor_base, 0),
                        .Class_debito_holerite_12 = IIf(intPosicaoInicioCorpo + 12 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 12 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 12)).Class_debito_holerite, 0),
                        .Class_credito_holerite_12 = IIf(intPosicaoInicioCorpo + 12 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 12 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 12)).Class_credito_holerite, 0),
                        .Class_rubrica_13 = IIf(intPosicaoInicioCorpo + 13 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 13 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 13)).Class_rubrica, ""),
                        .Class_descricao_13 = IIf(intPosicaoInicioCorpo + 13 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 13 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 13)).Class_descricao, ""),
                        .Class_QTO_13 = IIf(intPosicaoInicioCorpo + 13 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 13 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 13)).Class_QTO, 0),
                        .Class_UN_13 = IIf(intPosicaoInicioCorpo + 13 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 13 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 13)).Class_UN, ""),
                        .Class_base_INSS_13 = IIf(intPosicaoInicioCorpo + 13 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 13 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 13)).Class_base_INSS, ""),
                        .Class_base_FGTS_13 = IIf(intPosicaoInicioCorpo + 13 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 13 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 13)).Class_base_FGTS, ""),
                        .Class_base_IR_13 = IIf(intPosicaoInicioCorpo + 13 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 13 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 13)).Class_base_IR, ""),
                        .Class_tipo_financeiro_13 = IIf(intPosicaoInicioCorpo + 13 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 13 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 13)).Class_tipo_financeiro, ""),
                        .Class_valor_13 = IIf(intPosicaoInicioCorpo + 13 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 13 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 13)).Class_valor, 0),
                        .Class_valor_base_13 = IIf(intPosicaoInicioCorpo + 13 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 13 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 13)).Class_valor_base, 0),
                        .Class_debito_holerite_13 = IIf(intPosicaoInicioCorpo + 13 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 13 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 13)).Class_debito_holerite, 0),
                        .Class_credito_holerite_13 = IIf(intPosicaoInicioCorpo + 13 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 13 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 13)).Class_credito_holerite, 0),
                        .Class_rubrica_14 = IIf(intPosicaoInicioCorpo + 14 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 14 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 14)).Class_rubrica, ""),
                        .Class_descricao_14 = IIf(intPosicaoInicioCorpo + 14 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 14 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 14)).Class_descricao, ""),
                        .Class_QTO_14 = IIf(intPosicaoInicioCorpo + 14 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 14 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 14)).Class_QTO, 0),
                        .Class_UN_14 = IIf(intPosicaoInicioCorpo + 14 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 14 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 14)).Class_UN, ""),
                        .Class_base_INSS_14 = IIf(intPosicaoInicioCorpo + 14 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 14 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 14)).Class_base_INSS, ""),
                        .Class_base_FGTS_14 = IIf(intPosicaoInicioCorpo + 14 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 14 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 14)).Class_base_FGTS, ""),
                        .Class_base_IR_14 = IIf(intPosicaoInicioCorpo + 14 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 14 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 14)).Class_base_IR, ""),
                        .Class_tipo_financeiro_14 = IIf(intPosicaoInicioCorpo + 14 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 14 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 14)).Class_tipo_financeiro, ""),
                        .Class_valor_14 = IIf(intPosicaoInicioCorpo + 14 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 14 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 14)).Class_valor, 0),
                        .Class_valor_base_14 = IIf(intPosicaoInicioCorpo + 14 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 14 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 14)).Class_valor_base, 0),
                        .Class_debito_holerite_14 = IIf(intPosicaoInicioCorpo + 14 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 14 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 14)).Class_debito_holerite, 0),
                        .Class_credito_holerite_14 = IIf(intPosicaoInicioCorpo + 14 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 14 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 14)).Class_credito_holerite, 0),
                        .Class_rubrica_15 = IIf(intPosicaoInicioCorpo + 15 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 15 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 15)).Class_rubrica, ""),
                        .Class_descricao_15 = IIf(intPosicaoInicioCorpo + 15 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 15 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 15)).Class_descricao, ""),
                        .Class_QTO_15 = IIf(intPosicaoInicioCorpo + 15 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 15 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 15)).Class_QTO, 0),
                        .Class_UN_15 = IIf(intPosicaoInicioCorpo + 15 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 15 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 15)).Class_UN, ""),
                        .Class_base_INSS_15 = IIf(intPosicaoInicioCorpo + 15 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 15 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 15)).Class_base_INSS, ""),
                        .Class_base_FGTS_15 = IIf(intPosicaoInicioCorpo + 15 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 15 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 15)).Class_base_FGTS, ""),
                        .Class_base_IR_15 = IIf(intPosicaoInicioCorpo + 15 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 15 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 15)).Class_base_IR, ""),
                        .Class_tipo_financeiro_15 = IIf(intPosicaoInicioCorpo + 15 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 15 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 15)).Class_tipo_financeiro, ""),
                        .Class_valor_15 = IIf(intPosicaoInicioCorpo + 15 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 15 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 15)).Class_valor, 0),
                        .Class_valor_base_15 = IIf(intPosicaoInicioCorpo + 15 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 15 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 15)).Class_valor_base, 0),
                        .Class_debito_holerite_15 = IIf(intPosicaoInicioCorpo + 15 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 15 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 15)).Class_debito_holerite, 0),
                        .Class_credito_holerite_15 = IIf(intPosicaoInicioCorpo + 15 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 15 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 15)).Class_credito_holerite, 0),
                        .Class_rubrica_16 = IIf(intPosicaoInicioCorpo + 16 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 16 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 16)).Class_rubrica, ""),
                        .Class_descricao_16 = IIf(intPosicaoInicioCorpo + 16 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 16 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 16)).Class_descricao, ""),
                        .Class_QTO_16 = IIf(intPosicaoInicioCorpo + 16 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 16 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 16)).Class_QTO, 0),
                        .Class_UN_16 = IIf(intPosicaoInicioCorpo + 16 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 16 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 16)).Class_UN, ""),
                        .Class_base_INSS_16 = IIf(intPosicaoInicioCorpo + 16 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 16 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 16)).Class_base_INSS, ""),
                        .Class_base_FGTS_16 = IIf(intPosicaoInicioCorpo + 16 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 16 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 16)).Class_base_FGTS, ""),
                        .Class_base_IR_16 = IIf(intPosicaoInicioCorpo + 16 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 16 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 16)).Class_base_IR, ""),
                        .Class_tipo_financeiro_16 = IIf(intPosicaoInicioCorpo + 16 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 16 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 16)).Class_tipo_financeiro, ""),
                        .Class_valor_16 = IIf(intPosicaoInicioCorpo + 16 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 16 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 16)).Class_valor, 0),
                        .Class_valor_base_16 = IIf(intPosicaoInicioCorpo + 16 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 16 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 16)).Class_valor_base, 0),
                        .Class_debito_holerite_16 = IIf(intPosicaoInicioCorpo + 16 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 16 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 16)).Class_debito_holerite, 0),
                        .Class_credito_holerite_16 = IIf(intPosicaoInicioCorpo + 16 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 16 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 16)).Class_credito_holerite, 0),
                        .Class_rubrica_17 = IIf(intPosicaoInicioCorpo + 17 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 17 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 17)).Class_rubrica, ""),
                        .Class_descricao_17 = IIf(intPosicaoInicioCorpo + 17 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 17 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 17)).Class_descricao, ""),
                        .Class_QTO_17 = IIf(intPosicaoInicioCorpo + 17 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 17 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 17)).Class_QTO, 0),
                        .Class_UN_17 = IIf(intPosicaoInicioCorpo + 17 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 17 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 17)).Class_UN, ""),
                        .Class_base_INSS_17 = IIf(intPosicaoInicioCorpo + 17 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 17 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 17)).Class_base_INSS, ""),
                        .Class_base_FGTS_17 = IIf(intPosicaoInicioCorpo + 17 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 17 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 17)).Class_base_FGTS, ""),
                        .Class_base_IR_17 = IIf(intPosicaoInicioCorpo + 17 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 17 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 17)).Class_base_IR, ""),
                        .Class_tipo_financeiro_17 = IIf(intPosicaoInicioCorpo + 17 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 17 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 17)).Class_tipo_financeiro, ""),
                        .Class_valor_17 = IIf(intPosicaoInicioCorpo + 17 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 17 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 17)).Class_valor, 0),
                        .Class_valor_base_17 = IIf(intPosicaoInicioCorpo + 17 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 17 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 17)).Class_valor_base, 0),
                        .Class_debito_holerite_17 = IIf(intPosicaoInicioCorpo + 17 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 17 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 17)).Class_debito_holerite, 0),
                        .Class_credito_holerite_17 = IIf(intPosicaoInicioCorpo + 17 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 17 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 17)).Class_credito_holerite, 0),
                        .Class_rubrica_18 = IIf(intPosicaoInicioCorpo + 18 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 18 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 18)).Class_rubrica, ""),
                        .Class_descricao_18 = IIf(intPosicaoInicioCorpo + 18 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 18 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 18)).Class_descricao, ""),
                        .Class_QTO_18 = IIf(intPosicaoInicioCorpo + 18 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 18 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 18)).Class_QTO, 0),
                        .Class_UN_18 = IIf(intPosicaoInicioCorpo + 18 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 18 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 18)).Class_UN, ""),
                        .Class_base_INSS_18 = IIf(intPosicaoInicioCorpo + 18 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 18 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 18)).Class_base_INSS, ""),
                        .Class_base_FGTS_18 = IIf(intPosicaoInicioCorpo + 18 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 18 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 18)).Class_base_FGTS, ""),
                        .Class_base_IR_18 = IIf(intPosicaoInicioCorpo + 18 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 18 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 18)).Class_base_IR, ""),
                        .Class_tipo_financeiro_18 = IIf(intPosicaoInicioCorpo + 18 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 18 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 18)).Class_tipo_financeiro, ""),
                        .Class_valor_18 = IIf(intPosicaoInicioCorpo + 18 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 18 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 18)).Class_valor, 0),
                        .Class_valor_base_18 = IIf(intPosicaoInicioCorpo + 18 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 18 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 18)).Class_valor_base, 0),
                        .Class_debito_holerite_18 = IIf(intPosicaoInicioCorpo + 18 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 18 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 18)).Class_debito_holerite, 0),
                        .Class_credito_holerite_18 = IIf(intPosicaoInicioCorpo + 18 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 18 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 18)).Class_credito_holerite, 0),
                        .Class_rubrica_19 = IIf(intPosicaoInicioCorpo + 19 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 19 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 19)).Class_rubrica, ""),
                        .Class_descricao_19 = IIf(intPosicaoInicioCorpo + 19 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 19 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 19)).Class_descricao, ""),
                        .Class_QTO_19 = IIf(intPosicaoInicioCorpo + 19 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 19 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 19)).Class_QTO, 0),
                        .Class_UN_19 = IIf(intPosicaoInicioCorpo + 19 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 19 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 19)).Class_UN, ""),
                        .Class_base_INSS_19 = IIf(intPosicaoInicioCorpo + 19 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 19 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 19)).Class_base_INSS, ""),
                        .Class_base_FGTS_19 = IIf(intPosicaoInicioCorpo + 19 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 19 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 19)).Class_base_FGTS, ""),
                        .Class_base_IR_19 = IIf(intPosicaoInicioCorpo + 19 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 19 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 19)).Class_base_IR, ""),
                        .Class_tipo_financeiro_19 = IIf(intPosicaoInicioCorpo + 19 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 19 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 19)).Class_tipo_financeiro, ""),
                        .Class_valor_19 = IIf(intPosicaoInicioCorpo + 19 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 19 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 19)).Class_valor, 0),
                        .Class_valor_base_19 = IIf(intPosicaoInicioCorpo + 19 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 19 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 19)).Class_valor_base, 0),
                        .Class_debito_holerite_19 = IIf(intPosicaoInicioCorpo + 19 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 19 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 19)).Class_debito_holerite, 0),
                        .Class_credito_holerite_19 = IIf(intPosicaoInicioCorpo + 19 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 19 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 19)).Class_credito_holerite, 0),
                        .Class_rubrica_20 = IIf(intPosicaoInicioCorpo + 20 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 20 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 20)).Class_rubrica, ""),
                        .Class_descricao_20 = IIf(intPosicaoInicioCorpo + 20 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 20 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 20)).Class_descricao, ""),
                        .Class_QTO_20 = IIf(intPosicaoInicioCorpo + 20 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 20 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 20)).Class_QTO, 0),
                        .Class_UN_20 = IIf(intPosicaoInicioCorpo + 20 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 20 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 20)).Class_UN, ""),
                        .Class_base_INSS_20 = IIf(intPosicaoInicioCorpo + 20 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 20 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 20)).Class_base_INSS, ""),
                        .Class_base_FGTS_20 = IIf(intPosicaoInicioCorpo + 20 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 20 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 20)).Class_base_FGTS, ""),
                        .Class_base_IR_20 = IIf(intPosicaoInicioCorpo + 20 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 20 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 20)).Class_base_IR, ""),
                        .Class_tipo_financeiro_20 = IIf(intPosicaoInicioCorpo + 20 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 20 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 20)).Class_tipo_financeiro, ""),
                        .Class_valor_20 = IIf(intPosicaoInicioCorpo + 20 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 20 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 20)).Class_valor, 0),
                        .Class_valor_base_20 = IIf(intPosicaoInicioCorpo + 20 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 20 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 20)).Class_valor_base, 0),
                        .Class_debito_holerite_20 = IIf(intPosicaoInicioCorpo + 20 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 20 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 20)).Class_debito_holerite, 0),
                        .Class_credito_holerite_20 = IIf(intPosicaoInicioCorpo + 20 <= intPosicaoFimCorpo, hol_corp(IIf(intPosicaoInicioCorpo + 20 > intIndiceMaximo, 0, intPosicaoInicioCorpo + 20)).Class_credito_holerite, 0)
                        }
                        )
                intPosicaoInicioCorpo = intPosicaoFimCorpo + 1

            Next


        Catch ex As Exception

            MsgBox("Problemas ApontaAcoes!")

        End Try

        Return lista

    End Function

End Class
