Public Class ClassCol_pesq

    Public Property Id As Integer
    Public Property Chave As String
    Public Property CPF As String
    Public Property Nome As String
    Public Property Nascimento As String
    Public Property RG As String
    Public Property RGoe As String
    Public Property RGuf As String
    Public Property RGemissao As String
    Public Property RGvalidade As String
    Public Property CTPS As String
    Public Property CTPSoe As String
    Public Property CTPSuf As String
    Public Property CTPSserie As String
    Public Property CTPSemissao As String
    Public Property CTPSvalidade As String
    Public Property CNH As String
    Public Property CNHoe As String
    Public Property CNHuf As String
    Public Property CNHemissao As String
    Public Property CNHvalidade As String
    Public Property CNH1habilitacao As String
    Public Property PIS As String
    Public Property PISoe As String
    Public Property PISoeUF As String
    Public Property PISemissao As String
    Public Property PISvalidade As String
    Public Property Reservista As String
    Public Property ReservistaOE As String
    Public Property ReservistaOEuf As String
    Public Property ReservistaEmissao As String
    Public Property ReservistaValidade As String
    Public Property TituloNumero As String
    Public Property TituloOE As String
    Public Property TituloOEuf As String
    Public Property TituloZona As String
    Public Property TituloSecao As String
    Public Property TituloEmissao As String
    Public Property TituloValidade As String
    Public Property Mae As String
    Public Property MaeCPF As String
    Public Property MaeNascimento As String
    Public Property MaeFone As String
    Public Property Pai As String
    Public Property PaiCPF As String
    Public Property PaiNascimento As String
    Public Property PaiFone As String
    Public Property EstadoCivil As String
    Public Property UniaoEstavel As String
    Public Property Sexo As String
    Public Property EsposoNome As String
    Public Property EsposoCPF As String
    Public Property EsposoNascimento As String
    Public Property EsposoFone As String
    Public Property CompanheiroNome As String
    Public Property CompanheiroCPF As String
    Public Property CompanheiroNascimento As String
    Public Property CompanheiroFone As String
    Public Property Residencia As String
    Public Property ResidenciaCidade As String
    Public Property ResidenciaUF As String
    Public Property ResidenciaCEP As String
    Public Property Fone1 As String
    Public Property Fone2 As String
    Public Property Email As String
    Public Property AutorizaEmail As String
    Public Property Instrucao As String
    Public Property Curso As String
    Public Property ConselhoRegional As String
    Public Property ConselhoRegionalNumero As String
    Public Property ConselhoRegionalData As String
    Public Property ConselhoRegionalOE As String
    Public Property Banco As String
    Public Property Agencia As String
    Public Property ContaCorrente As String
    Public Property ContaCorrenteDigito As String
    Public Property Dependente1Parentesco As String
    Public Property Dependente1Nome As String
    Public Property Dependente1CPF As String
    Public Property Dependente1Nascimento As String
    Public Property Dependente2Parentesco As String
    Public Property Dependente2Nome As String
    Public Property Dependente2CPF As String
    Public Property Dependente2Nascimento As String
    Public Property Dependente3Parentesco As String
    Public Property Dependente3Nome As String
    Public Property Dependente3CPF As String
    Public Property Dependente3Nascimento As String
    Public Property Dependente4Parentesco As String
    Public Property Dependente4Nome As String
    Public Property Dependente4CPF As String
    Public Property Dependente4Nascimento As String
    Public Property Dependente5Parentesco As String
    Public Property Dependente5Nome As String
    Public Property Dependente5CPF As String
    Public Property Dependente5Nascimento As String
    Public Property Dependente6Parentesco As String
    Public Property Dependente6Nome As String
    Public Property Dependente6CPF As String
    Public Property Dependente6Nascimento As String
    Public Property Altura As String
    Public Property Peso As String
    Public Property Cabelo As String
    Public Property Olhos As String
    Public Property TipoDeSangues As String
    Public Property Cor As String
    Public Property Deficiente As String
    Public Property DeficienteTipo As String
    Public Property DeficienteOutros As String
    Public Property ContatoNome1 As String
    Public Property ContatoNome1Telefone As String
    Public Property ContatoNome1Conhecimento As String
    Public Property ContatoNome2 As String
    Public Property ContatoNome2telefone As String
    Public Property ContatoNome2Conhecimento As String
    Public Property EmpresaNome1 As String
    Public Property EmpresaNome1Contato As String
    Public Property EmpresaNome1Telefone As String
    Public Property EmpresaNome2 As String
    Public Property EmpresaNome2Contato As String
    Public Property EmpresaNome2Telefone As String
    Public Property Cargo As String
    Public Property NomeCracha As String
    Public Property ASOadmissao As String
    Public Property Admissao As String
    Public Property AdmissaoReferencia As String
    Public Property CadastroDataHora As String
    Public Property UsuarioCadastroResponsavel As String
    Public Property Status As String
    Public Property PIX As String
    Public Property SalarioAtual As String
    Public Property HorasTrabalhadasSemana As String
    Public Property DiasDescansoSemana As String
    Public Property ResidenciaBairro As String
    Public Property RescisaoData As String
    Public Property ASOrescisao As String
    Public Property DependentesIR As String
    Public Property DependentesSF As String
    Public Property CBO As String
    Public Property Setor As String
    Public Property Dependente1IR As String
    Public Property Dependente1SF As String
    Public Property Dependente2IR As String
    Public Property Dependente2SF As String
    Public Property Dependente3IR As String
    Public Property Dependente3SF As String
    Public Property Dependente4IR As String
    Public Property Dependente4SF As String
    Public Property Dependente5IR As String
    Public Property Dependente5SF As String
    Public Property Dependente6IR As String
    Public Property Dependente6SF As String
    Public Property Categoria As String
    Public Property ContratoTipo As String
    Public Property Empresa As String
    Public Property DepTotal As Integer
    Public Property PixIdentificacao As String

End Class
